import React from "react";
import { Link } from "react-router-dom";

function TermsAndConditions() {
  return (
    <div>
      <div className="bg-gray-100 h-screen overflow-auto py-2 px-2 text-justify">
        <div className="w-full mx-auto bg-white rounded-lg shadow-md p-6">
              <div>
                <p className=" font-semibold text-gray-800 mb-2 text-sm">
                  This Terms of Use is a legal agreement between Government of
                  Telangana and You stating the terms that govern Your use of
                  the Portal (defined below).
                </p>
                <p className="text-gray-500 mb-4 text-sm">
                  This document is an electronic record in terms of the
                  information technology act, 2000, and the rules thereunder as
                  applicable and the amended provisions pertaining to electronic
                  records in various statutes as amended by the information
                  technology act, 2000. This electronic record is generated by a
                  computer system and does not require any physical or digital
                  signatures.
                </p>
                <p className="text-gray-500 mb-4 text-sm">
                  If you do not agree to be bound or cannot comply with any of
                  the Terms of Use or the Privacy Policy, please do not continue
                  with availing the services on our Portal. Your act of clicking
                  on/ checking the
                  <b className="text-sm font-semibold text-gray-800 mb-2">
                    {" "}
                    "I agree" tab
                  </b>
                  / box below or using the services offered on this Portal shall
                  be deemed as agreement to these Terms of Use and the Privacy
                  Policy.
                </p>
                <p className="text-gray-500 mb-4 text-sm">
                  By using our services, websites, or software applications{" "}
                  <b className="text-sm font-semibold text-gray-800 mb-2">
                    (“Service”, “App”, “Application(s)”, “SMS”, “MeeSeva App”)
                  </b>
                  , you are entering into a binding contract with Electronic
                  Service Delivery, ITE&amp;C Department, Government of
                  Telangana{" "}
                  <b className="text-sm font-semibold text-gray-800 mb-2">
                    (“we”, “us”, “our”, “ESD”, “ITE&amp;C”, “GoT”)
                  </b>
                  . Your agreement with us includes these Terms and Conditions
                  of Use (“Terms”) and our Privacy Policy. If you don’t agree
                  with these Terms, then please don’t use the Service.
                </p>
                <p className="text-gray-500 mb-4 text-sm">
                  Accessing, browsing or otherwise using the portal indicates
                  your agreement to all the terms and conditions under these
                  terms of use, so please read the terms of use carefully before
                  proceeding.
                </p>
                <p className="text-gray-500 mb-4 text-sm"> You shall hereinafter be referred to as{" "}
                <b className="text-sm font-semibold text-gray-800 mb-2">
                  "Party”.
                </b>
                </p>
                <div classname="row cont-mp">
                  <ul className="list-disc">
                    <li>
                      <p className="text-base font-semibold text-gray-800 my-3">
                        1. GENERAL TERMS
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        Your use of the Portal is governed by the following
                        Terms of Use. Unless otherwise specified, You hereby
                        represent and warrant that You are an individual aged
                        eighteen (18) years or above and are a resident of
                        India. For the purposes of these Terms of Use, whenever
                        the context so requires 'You' or 'Your' shall mean any
                        natural or legal person who is (i) accessing the Portal
                        by providing Registration Data while registering on the
                        Portal as a Registered User. You cannot browse and/ or
                        use the Portal without becoming a Registered User. When
                        You use any of the services provided on the Portal, You
                        will be subject to these Terms of Use including any
                        laws, rules, guidelines, policies, terms, and conditions
                        applicable to such service, and they shall be deemed to
                        be incorporated into this Terms of Use and shall be
                        considered as part of this Terms of Use. GoT reserves
                        the right, at their sole discretion, to change, modify,
                        add or remove portions of these Terms of Use, at any
                        time without any prior written notice to You. It is Your
                        responsibility to review these Terms of Use periodically
                        for updates/ changes. You shall be bound by any such
                        revisions. If You do not agree to the revised Terms of
                        Use and/ or the Privacy Policy, then GoT shall cease to
                        provide the services to You through the Portal. If at
                        any time You violate the Terms of Use stated herein and/
                        or the Privacy Policy, then GoT reserves the right to
                        cease to provide the services to You.
                      </p>
                    </li>
                    <li>
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        2. REGISTRATION
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        User agrees and understands that being a Registered User
                        is a mandatory requirement for using the services on the
                        Portal. Registration on the Portal is free. User agrees
                        to provide any and all information sought by the Portal
                        at the time of registration, including without
                        limitation the User's name, email address, city, phone
                        number etc.
                        <b className="text-sm font-semibold text-gray-800 mb-2">
                          ("Registration Data").
                        </b>{" "}
                        The User's mobile phone number shall be the log-in name
                        and a password/ PIN shall be sent to the user{" "}
                        <b className="text-sm font-semibold text-gray-800 mb-2">
                          ("Log-in Details").
                        </b>{" "}
                        "User" shall mean any natural/ legal person who accesses
                        or uses the Portal. For the purpose of this Terms of Use
                        the term 'legal person' shall include a company, a
                        partnership, association, society or any such legal
                        entity as recognized under the applicable laws.
                        <b className="text-sm font-semibold text-gray-800 mb-2">
                          "Registered User"
                        </b>{" "}
                        shall mean any natural/ legal person who has been
                        registered on the Portal after the completion of the
                        verification process.
                      </p>
                    </li>


                    <li>
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                      3. TERMS OF USE
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">By agreeing to use/ avail the services, You represent, warrant, undertake and confirm that -</p>
                      <ul className="ps-6 list-disc">
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">I.</span>The Registration Data provided by You is true, current, complete and accurate in all respects. You agree to promptly update Your Registration Data, in case of any change, so that Your information remains true, current, complete, and accurate at all times.</li>
                                                <li  className="text-sm mb-2"><span className="font-serif pe-2">II.</span>If You have registered on the Portal on behalf of any company, partnership firm, limited liability partnership and/ or anybody corporate, then You have the complete right and authority to provide the Registration data, create an account on the Portal, access the Portal and/ or deal on behalf of and bind such company, partnership firm, limited liability partnership or body corporate;</li>
                                                <li  className="text-sm mb-2"><span className="font-serif pe-2">III.</span>Your Registration Data and any other personal data collected by the Portal is subject to the Portal's Privacy Policy. The Portal may collect information such as occupation, mobile phone number, email address, language, zip code, area code, unique device identifier, location, customer preferences, and the time zone, where the services are used</li>
                                                <li  className="text-sm mb-2"><span className="font-serif pe-2">IV.</span>GoT may access, preserve, and disclose Your Registration Data subject to the Privacy Policy, if required to do so by law or in a good faith and belief that such access, preservation, or disclosure is reasonably necessary to: (a) comply with legal process and/ or any applicable law in the territory; (b) enforce the Terms of Use; (c) respond to Your requests for customer service; or (d) protect the rights, property or personal safety of GoT, affiliates, its users and the public.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">V.</span>GoT shall be entitled to suspend, without any prior notice to You, Your access to the whole or any part of the services and/ or the Portal if in the opinion of GoT you have acted in contravention of these Terms and Conditions. GoT further has the right to temporarily suspend access to the whole or any part of the services and/ or the Portal for any technical/ operational reason. GoT may, but shall not be obliged to, give You as much notice of any interruption of access to the services as is reasonably practicable. GoT will restore access to the services as soon as it is reasonably practicable after temporary suspension. You agree that such decision shall be based on the sole discretion of GoT and any decision taken in this regard shall be final and binding on You.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">VI.</span>Your participation on the Portal is at GoT's discretion. GoT reserves the right to disallow your participation on the Portal. </li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">VII.</span>GoT shall be under no liability whatsoever to You in the event of non-availability of the Portal or any portion thereof occasioned by Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, failure of any public utility, industrial action, man-made disaster, satellite failure or any other cause whatsoever beyond the control of GoT, and if such inability to perform such obligation continues for a period of 15 (fifteen) days, then GoT shall be at liberty and entitled in their sole discretion to cancel any services to You forthwith and such decision shall be final and binding.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">VIII.</span>You shall not either directly or through the use of any device, software, internet site, web-based service, or other means remove, alter, bypass, avoid, interfere with, or circumvent any copyright, trademark, or other proprietary notices marked on the Content or any digital rights management mechanism, device, or other content protection or access control measure associated with the Content including geo-filtering mechanisms. Further, You agree not to either directly or through the use of any device, software, internet site, web-based service, or other means copy, download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the Content or create any derivative work and/ or material based on the Content. For the purposes of these Terms of Use, 'Content' means all visible and background material available on the Portal, including any proprietary material, GoT logo, GoT trade-mark, trade-name belonging to GoT and any material which is owned by GoT and information which may not be owned by GoT.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">IX.</span>You will not hyperlink urls of other sites and/ or insert interstitial ads and/ or promotion webpages, upload malware, Trojan and/ or any virus on the Portal.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">X.</span>You agree that GoT retains all rights to the Content. You further agree that the Content You access and view as part of the services may include information, data, services and materials which is neither owned nor controlled by GoT. The Content is protected by copyright, trademark, and other laws related to intellectual property. You undertake not to challenge and/ or dispute GoT's ownership of its trademark, trade name and/ or the GoT logo available on the Portal, at any time in any part of the world.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">XI.</span>You are responsible for the security and proper use of Your unique Log-in Details that You enter while registering on the Portal and must take all necessary steps to ensure that they are kept confidential, used properly, and not disclosed to unauthorized persons.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">XII.</span>For the avoidance of doubt, by submitting any information including communication, offer, e-mail, You represent that the information or contents thereof are not confidential or comprise any sensitive personal information. For the purposes of these Terms of Use, "Sensitive Personal Information" shall bear the meaning ascribed to it under the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and shall include information relating to password; financial information such as bank account or credit card or debit card or other payment instrument details; physical, physiological and mental health condition; sexual orientation; medical records and history; bio-metric information.</li>
                                                <li className="text-sm mb-2"><span className="font-serif pe-2">XIII.</span>
                                                    You shall not host, display, upload, modify, communicate, publish, transmit, update or share any information or product/ goods/ item that -
                                                    <div className="ms-6">
                                                        <ul className="list-style ps-4">
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">a.</span> belongs to another person and/or to which You do not have any right to;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">b.</span> is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">c.</span> harm minors in any way;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">d.</span> infringes any patent, trademark, copyright or other proprietary rights;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">e.</span> violates any law for the time being in force;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">f.</span> deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">g.</span> impersonates another person;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">h.</span> contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">i.</span> threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation. You also represent and warrant that your use of the Portal and your act of posting any information/ data on the Portal does not violate any right of any party, including privacy rights, publicity rights, and intellectual property rights;</li>
                                                            <li className="text-sm mb-2"><span className="font-serif pe-2">j.</span> is false, misleading or inaccurate.</li>
                                                        </ul>
                                                    </div>
                                                </li>
                                            </ul>
                    </li>


                    <li className="text-gray-500 mb-4 text-sm">
                      You shall not attempt to gain unauthorized access to any
                      portion or feature of the Portal, or any other systems or
                      networks connected to the Portal or to any server,
                      computer, network, or to any of the services offered on or
                      through the Portal, by hacking, password "mining" or any
                      other illegitimate means.
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      GoT may discontinue any features, functionality of the
                      Portal at its sole discretion
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      As long as You comply with these Terms of Use, GoT grants
                      You a personal, limited, non-exclusive, non-transferable,
                      revocable privilege to enter and use the Portal and avail
                      the services therein ("License").
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      You confirm, agree and represent that Your act of availing
                      services on the Portal including execution of the Terms of
                      Use including any earlier agreements between the Parties
                      shall supersede all and any agreements/ arrangements,
                      which You may have with third parties and will have no
                      bearing on any portion of the Terms of Use including any
                      other written agreement between You and GoT.
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      Whether or not You accede to/ execute the terms of use
                      and/ or privacy policy of the third party service provider
                      rendering services on the Portal, You will be bound by the
                      terms and conditions set out by such third party service
                      provider in the event that You avail any services from
                      such third party.
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        4. COMMUNICATION
                      </p>
                      <div>
                        Upon use of the Portal, You agree and understand that
                        You are communicating with GoT through electronic
                        records and You consent to receive communications via
                        electronic records from GoT. You agree that all
                        agreements, notices, disclosures and other
                        communications that GoT provides to You electronically
                        satisfy any legal requirement that such communications
                        be in writing. You additionally agree and understand
                        that You shall be receiving email communication with
                        respect to all and any Transactions relating to You.
                      </div>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        5. PLATFORM FOR COMMUNICATION
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        The Portal is merely a platform hosted for Registered
                        Users to facilitate their transaction and availing
                        different services available on the Portal. GoT and/ or
                        any of its authorized representative including IMI
                        Mobile, is not a negotiating party at any point and is
                        merely a conduit of communication/ intermediary of
                        offers and services by various third parties. <br />
                        In light of the above, You acknowledge that -
                      </p>
                      <ul >
                        <li className="text-gray-500 mb-4 text-sm">
                          Any and all commercial/ contractual terms are offered
                          by and agreed to between Registered Users and third
                          party service providers alone and the service provider
                          and service receiver are solely responsible for
                          fulfilling the commercial/ contractual terms. The
                          commercial/ contractual terms may include without
                          limitation price, shipping costs, payment methods,
                          payment terms, date, period and mode of delivery,
                          warranties related to products and services and after
                          sales services related to products and services. GoT
                          does not have any control or does not determine or
                          advise or in any way involve itself in the offering or
                          acceptance of such commercial/ contractual terms
                          between the service providers and service receivers;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives do
                          not make any representation or give a warranty as to
                          specifics (such as quality, value, scalability,
                          merchantability etc.) of the products or services
                          proposed to be sold or offered to be sold or purchased
                          on the Portal. GoT does not implicitly or explicitly
                          support or endorse the sale or purchase of any
                          products or services on the Portal. GoT and/ or any of
                          its authorized representatives accepts no liability
                          for any errors or omissions, whether on behalf of
                          itself, its affiliates or third parties;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives do
                          not initiate/ control/ monitor all of the content/
                          applications made available on the Portal, and
                          therefore such content/ applications may be changed/
                          modified/ varied / withdrawn/ substituted/ replaced by
                          the relevant service provider at any time with or
                          without any notice to You. In the event of the
                          happening of any of the foregoing, GoT, and their
                          authorized representatives shall not in any manner be
                          responsible or liable for any change, variation,
                          modification, withdrawal, substitution, or replacement
                          of the content/ application;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT, or any of their authorized representatives do not
                          control the availability or functionality of any of
                          the individual content/ applications made available by
                          service providers/ third parties on the Portal, and
                          shall not at any time be liable or responsible for any
                          non-availability, defects, glitches, or errors, in any
                          content/ applications;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives is
                          not responsible for any non-performance or breach of
                          any contract entered into between the third party
                          service providers and service receivers and You agree
                          not to hold GoT and/ or any of its authorized
                          representatives responsible for the same. GoT and/ or
                          any of its authorized representatives cannot and does
                          not guarantee that the concerned service providers
                          and/ or service receivers will perform any transaction
                          concluded on the Portal. GoT and/ or any of its
                          authorized representatives shall not and is not
                          required to mediate or resolve any dispute or
                          disagreement between the service providers and service
                          receivers. To that extent and to the extent permitted
                          under law, You agree to not make GoT and/ or any of
                          its authorized representatives a party to any suit
                          vis-à-vis any dispute in transaction with a third
                          party;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives does
                          not make any representation or warranty as to the
                          item-specifics (such as legal title, credit
                          worthiness, identity, etc) of any of its users
                          including service providers and/ or service receivers.
                          You are advised to independently verify the bona fides
                          of any particular user that You choose to deal with on
                          the Portal and use Your best judgment on that behalf;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives does
                          not at any point of time during any transaction
                          between You and the service provider, as the case
                          maybe on the Portal come into or take possession of
                          any of the products or services offered by service
                          provider, as the case maybe nor does it at any point
                          gain title to or have any rights or claims over the
                          products or services offered by service provider to
                          You;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          At no time shall GoT and/ or any of its authorized
                          representatives hold any right, title or interest over
                          the products offered by any third party service
                          providers on the Portal nor shall GoT and/or any of
                          its authorized representatives have any obligations or
                          liabilities in respect of such contract entered into
                          between You and the service providers, as the case
                          maybe. GoT and/ or any of its authorized
                          representatives is not responsible for unsatisfactory
                          or delayed performance of services or damages or
                          delays as a result of products which are out of stock,
                          unavailable or back ordered;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          You agree and acknowledge that You are initiating the
                          transmission on the Portal by selecting the receiver
                          of such transmission and/ or a third party service
                          provider on the Portal. The Portal is only a platform
                          that can be utilized by You to avail of products or
                          services at one place and any information in the
                          process will be transmitted to You directly without
                          any kind of interference, modification, alteration in
                          such information. You further agree and acknowledge
                          that GoT and/ or any of its authorized representatives
                          is neither initiating the transmission between You and
                          the service provider on the Portal, selecting the
                          receiver of any transmission on the Portal or
                          modifying/ amending/ changing the contents of any
                          transmission initiated between You and a service
                          provider on the Portal;
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          You release and indemnify GoT and/ or any of its
                          officers, authorized representatives including IMI
                          Mobile and its affiliates from any cost, damage,
                          liability or other consequences of any of the actions
                          of the users of the Portal and specifically waive any
                          claims that You may have in this behalf under any
                          applicable law. Notwithstanding its reasonable efforts
                          in that behalf, GoT cannot take responsibility or
                          control the information provided by other users of the
                          Portal and/ or third party service providers which is
                          made available on the Portal. You may find other
                          user's and/ or third party service providers
                          information to be offensive, harmful, inconsistent,
                          inaccurate, or deceptive. Please use caution and
                          practice safe trading when using the Portal.
                        </li>
                      </ul>
                      <p />
                    </li>
                    <li >
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        6. LINKED DESTINATIONS AND ADVERTISING
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        This Portal contains advertising and other material
                        submitted to GoT by third parties. Although acceptance
                        of advertisements on the Portal on request is subject to
                        GoT's terms and conditions, GoT expressly disclaims any
                        liability arising out of the usage of these products or
                        services advertised on the Portal. The Portal may
                        contain articles on various topics contributed by
                        several individuals and third party content aggregators
                        and service providers. The views are exclusively their
                        own and do not represent the views of GoT, affiliates
                        and/ or its management or authorized representative. All
                        liability is excluded to the extent permitted by law
                        including any implied terms. Indian law and jurisdiction
                        applies with respect to contents of the Portal. While
                        using the Portal for information purposes or otherwise,
                        You acknowledge and accept the above disclaimer and
                        agree to do so at Your own risk and You agree that GoT
                        is not liable for any loss or claim that You may have
                        basis such usage.
                      </p>
                      <ul >
                        <li className="text-gray-500 mb-4 text-sm">
                          If the Portal provides links to other websites and/ or
                          third party service providers, You should not infer or
                          assume that GoT and/ or any of its authorized
                          representatives operates, controls, or is otherwise
                          connected with these other websites. When You click on
                          a link on the Portal, it will not warn You that You
                          have left the services and are subject to the terms
                          and conditions (including privacy policies) of another
                          website. In some cases, it may be less obvious than
                          others that You have left the services and reached
                          another website or destination. Please be careful to
                          read the terms of use and privacy policy of any other
                          website or destination before you provide any
                          confidential information or engage in any
                          transactions. You should not rely on these Terms of
                          Use and/or Privacy Policy to govern Your use of
                          another website or destination.
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT is not responsible for the content or practices of
                          any service provider or website or destination or
                          application other than the Portal, even if it links to
                          the Portal and even if the service provider or website
                          or destination is operated by a company affiliated or
                          otherwise connected with or hosted on the Portal. By
                          using the services, You acknowledge and agree that GoT
                          and/ or any of its authorized representatives are not
                          responsible or liable to You for any content or other
                          materials hosted and served from any other service
                          provider or website or destination or application.
                        </li>
                        <li className="text-gray-500 mb-4 text-sm">
                          GoT and/ or any of its authorized representatives
                          takes no responsibility for advertisements or any
                          third party material posted on any of the Portal, nor
                          does it take any responsibility for the products or
                          services provided by service providers. Any dealings
                          You have with service providers found while using the
                          services are between You and the service provider, and
                          You agree that GoT is not liable for any loss or claim
                          that You may have against a service provider.
                        </li>
                      </ul>
                      <p />
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        7. INDEMNITY:
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        You agree to defend, indemnify and hold harmless GoT,
                        its affiliates, authorized representations, officers,
                        directors, employees and agents, from and against any
                        and all claims, damages, obligations, losses,
                        liabilities, costs or debt, and expenses (including but
                        not limited to attorney's fees) arising from: (i) Your
                        use of and access to the services on the Portal; (ii)
                        Your violation of any term of these Terms of Use and/ or
                        the Privacy Policy; (iii) Your violation of any third
                        party right, including without limitation any copyright,
                        property, or privacy right basis the user material; and
                        (iv) Your breach of any applicable laws. This
                        indemnification obligation will survive the expiry or
                        termination of Terms of Use and Your use of the service
                        on the Portal.
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        GoT, its affiliates, authorized representations,
                        officers, directors, employees and agents are in no
                        manner whatsoever responsible and/ or shall not be held
                        liable in any manner whatsoever, for any physical
                        injury, death, mental and/ or emotional trauma caused to
                        You in any manner whatsoever, in relation to the Portal
                        and/ or availing any services on the Portal.
                      </p>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        8. GOVERNING LAW:
                      </p>
                      <div>
                        You shall comply with the laws of India and/ or any laws
                        that may apply to You.
                        <br />
                        <p className="text-gray-500 mb-4 text-sm">
                          Notwithstanding the conflict of laws principle, the
                          Terms of Use shall be construed in accordance with the
                          laws of India and in case of any dispute or other
                          matter arising in reference to the use of the Portal
                          and/ or availing the services on the Portal shall be
                          referred to a sole arbitrator appointed by GoT and
                          shall be governed by the Arbitration and Conciliation
                          Act, 1996, amended from time to time. The venue for
                          arbitration shall be Hyderabad, and shall be conducted
                          in language. All the costs, charges and expenses in
                          connection to the Arbitration shall be solely borne by
                          You.
                        </p>
                        <p className="text-gray-500 mb-4 text-sm">
                          The arbitration shall be conducted in accordance with
                          the Arbitration and Conciliation Act, 1996 and rules
                          framed thereunder, as amended from time to time. The
                          arbitration proceedings shall be held in Hyderabad.
                          The courts of Hyderabad shall have exclusive
                          jurisdiction, the arbitration and all matters arising
                          in connection herewith. Notwithstanding the foregoing,
                          You agree that GoT has the right to bring any
                          proceedings before any court/ forum of competent
                          jurisdiction and You irrevocably submit to the
                          jurisdiction of such courts or forum.
                        </p>
                      </div>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        9. DISCLAIMER OF WARRANTIES:
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        GoT, its affiliates, authorized representatives and
                        service provider provide the Portal and services "as is"
                        and without any warranty or condition, express, implied
                        or statutory and specifically disclaim any implied
                        warranties of title, merchantability, fitness for a
                        particular purpose and non-infringement. You expressly
                        agree that Your use of the Portal is at Your own risk.
                      </p>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        10. LIMITATION OF LIABILITY:
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        In no case shall GoT, its directors, officers,
                        employees, affiliates, agents, contractors, principals,
                        or licensors or authorised representatives be liable for
                        any direct, indirect, incidental, punitive, special, or
                        consequential damages arising from your use of the
                        services or any content or material thereof or for any
                        other claim related in any way to your use of the
                        services or any content or material thereof, including,
                        but not limited to, any errors or omissions in any
                        content or material, or any loss or damage of any kind
                        incurred as a result of the use of the services or any
                        content or material thereof, even if advised of their
                        possibility. Where the laws do not allow the exclusion
                        or the limitation of liability for consequential or
                        incidental damages, in such jurisdictions, GoT's
                        liability shall be limited to the extent permitted by
                        law.
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        GoT does not warrant that product description or other
                        content of this Portal is accurate, complete, reliable,
                        current, or error-free and assumes no liability in this
                        regard.
                      </p>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        11. GENERAL:
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        If any provision of these Terms of Use is held invalid,
                        void, or unenforceable, then that provision shall be
                        considered severable from the remaining provisions, and
                        the remaining provisions given full force and effect.
                        <br />
                        You acknowledge that Your representations and
                        warranties, obligations and the clauses relating to
                        indemnities, limitation of liability, grant of license,
                        governing law, confidentiality shall survive the efflux
                        of time and the termination of these Terms of Use.
                        <br />
                        These Terms of Use and Privacy Policy constitute the
                        entire agreement by You governing Your use of the
                        services on the Portal, superseding any prior
                        agreements. <br />
                        You hereby acknowledge and agree that the relationship
                        between You and GoT and/ or any of its authorized
                        representatives and its/their affiliated companies is
                        not a confidential, fiduciary, or other special
                        relationship.
                      </p>
                    </li>
                    <li className="text-gray-500 mb-4 text-sm">
                      <p className="text-sm font-semibold text-gray-800 mb-2">
                        12. CONTACT:
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        If You have any questions, complaints or claims with
                        respect to the Portal and/or services, then such
                        correspondence should be directed to the address as
                        given below -<br />
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        Deputy Director (Technical), ESD, <br />
                        8-2-566, Road no. 7 Banjara Hills
                        <br />
                        Email:{" "}
                        <b className="text-sm font-semibold text-gray-600 mb-2">
                          dydir_tech_eseva@telangana.gov.in
                        </b>
                        <br />
                        Call Center Phone: 1100, 18004251110
                        <br />
                      </p>
                      <p className="text-gray-500 mb-4 text-sm">
                        You agree and acknowledge that owing to the evolving
                        nature of the services, these Terms of Use will be
                        amended from time to time. You shall be solely
                        responsible to keep yourself apprised of the changes
                        which will be reflected in this document from time to
                        time. GoT and/ or any of its authorized representatives
                        will not send any private communication to You of any
                        change. It is agreed that You will be bound to the
                        amended Terms of Use at all times.
                      </p>
                      <b className="text-sm font-semibold text-gray-800 mb-2">
                        This Terms of Use is an electronic record in terms of
                        Information Technology Act, 2000 and rules there under
                        as applicable and the amended provisions pertaining to
                        electronic records in various statutes as amended by the
                        Information Technology Act, 2000.
                        <br />
                        Any information gathered through this Terms of Use shall
                        be subject to our Privacy Policy which is incorporated
                        herein by reference and available at{" "}
                       
                          <Link to="/privacy" className="text-blue-600">[Privacy Policy]</Link>
                       
                      </b>{" "}
                      <p />
                    </li>
                  </ul>
                </div>
              </div>
          </div>
        </div>
      </div>
  );
}

export default TermsAndConditions;
